"""Static plugin inspection and reviewed local registration."""

from chulk.plugins.artifacts import (
    PluginArtifactError,
    PluginPackageStore,
    PreparedPluginPackage,
)
from chulk.plugins.catalog import (
    PluginCatalogError,
    ReviewedPluginCatalog,
)
from chulk.plugins.inspection import (
    PluginInspectionError,
    inspect_plugin_directory,
)
from chulk.plugins.locks import PluginLockError, PluginLockFile
from chulk.plugins.manifest import (
    PluginManifestError,
    load_plugin_manifest,
    plugin_manifest_from_mapping,
    resolve_plugin_resource,
)
from chulk.plugins.models import (
    AuditSeverity,
    FilesystemAccess,
    LoadedPluginEntryPoint,
    PLUGIN_LOCK_SCHEMA_VERSION,
    PLUGIN_MANIFEST_FILENAME,
    PLUGIN_MANIFEST_SCHEMA_VERSION,
    PluginAuditFinding,
    PluginAuditReport,
    PluginAuthorityDiff,
    PluginCatalogEntry,
    PluginCatalogSnapshot,
    PluginCatalogSource,
    PluginCategory,
    PluginDependency,
    PluginEntryPoint,
    PluginFilesystemRequirement,
    PluginInspection,
    PluginLifecycleAction,
    PluginLifecycleReceipt,
    PluginLockEntry,
    PluginManifest,
    PluginPackage,
    PluginRegistrationStatus,
    PluginRevocation,
    PluginReview,
    PluginSourceKind,
    PluginTrustState,
    PluginUpdatePlan,
)
from chulk.plugins.lifecycle import (
    PluginHistoryStore,
    PluginLifecycleError,
    PluginRecoveryPoint,
    PluginRevocationStore,
    plugin_authority_diff,
    validate_trusted_git_checkout,
)
from chulk.plugins.migrations import (
    PluginMigrationError,
    PluginMigrationManager,
    validate_forward_only_migrations,
)
from chulk.plugins.registry import (
    LocalPluginRegistry,
    PluginLoadError,
    PluginRegistrationError,
    PluginVerificationError,
)


__all__ = [
    "AuditSeverity",
    "FilesystemAccess",
    "LoadedPluginEntryPoint",
    "LocalPluginRegistry",
    "PLUGIN_LOCK_SCHEMA_VERSION",
    "PLUGIN_MANIFEST_FILENAME",
    "PLUGIN_MANIFEST_SCHEMA_VERSION",
    "PluginAuditFinding",
    "PluginAuditReport",
    "PluginArtifactError",
    "PluginAuthorityDiff",
    "PluginCatalogEntry",
    "PluginCatalogError",
    "PluginCatalogSnapshot",
    "PluginCatalogSource",
    "PluginCategory",
    "PluginDependency",
    "PluginEntryPoint",
    "PluginFilesystemRequirement",
    "PluginInspection",
    "PluginInspectionError",
    "PluginHistoryStore",
    "PluginLifecycleAction",
    "PluginLifecycleError",
    "PluginLifecycleReceipt",
    "PluginLoadError",
    "PluginLockError",
    "PluginLockFile",
    "PluginLockEntry",
    "PluginManifest",
    "PluginManifestError",
    "PluginMigrationError",
    "PluginMigrationManager",
    "PluginPackage",
    "PluginPackageStore",
    "PluginRecoveryPoint",
    "PluginRegistrationStatus",
    "PluginRevocation",
    "PluginRevocationStore",
    "PluginRegistrationError",
    "PluginReview",
    "PluginSourceKind",
    "PluginTrustState",
    "PluginUpdatePlan",
    "PluginVerificationError",
    "inspect_plugin_directory",
    "load_plugin_manifest",
    "plugin_manifest_from_mapping",
    "resolve_plugin_resource",
    "plugin_authority_diff",
    "PreparedPluginPackage",
    "ReviewedPluginCatalog",
    "validate_forward_only_migrations",
    "validate_trusted_git_checkout",
]
