"""Stable execution backend interfaces and the direct host implementation."""

from chulk.execution.base import ExecutionBackend, ExecutionSession
from chulk.execution.host import ExecutionContextLifecycle, HostExecutionBackend, HostExecutionSession
from chulk.execution.models import (
    ChangeApplicationResult,
    ChangeDisposition,
    ChangeRecord,
    ChangeSet,
    ChangeSetApproval,
    CommandExecutionRequest,
    ContainmentStatus,
    ExecutionPolicy,
    ExecutionResult,
    ExecutionSessionRequest,
    ExecutionWorkspace,
    FileListRequest,
    FileReadRequest,
    FileSearchRequest,
    FileWriteRequest,
    NetworkPolicy,
    PatchApplyRequest,
    ProcessHandle,
    WorkspaceMode,
    WorkspacePersistence,
)
from chulk.execution.policy import (
    EnvironmentPolicy,
    GitWorktreePolicy,
    ResourcePolicy,
    SecretPolicy,
    TransferPolicy,
    UnsafePathAction,
    WorkspaceMaterializationPolicy,
)
from chulk.execution.temporary import (
    GitWorktreeBackend,
    TemporaryWorkspaceBackend,
    TemporaryWorkspaceSession,
    WorkspacePolicyError,
)

__all__ = [
    "ChangeApplicationResult",
    "ChangeDisposition",
    "ChangeRecord",
    "ChangeSet",
    "ChangeSetApproval",
    "CommandExecutionRequest",
    "ContainmentStatus",
    "ExecutionBackend",
    "ExecutionContextLifecycle",
    "ExecutionPolicy",
    "ExecutionResult",
    "ExecutionSession",
    "ExecutionSessionRequest",
    "ExecutionWorkspace",
    "EnvironmentPolicy",
    "FileListRequest",
    "FileReadRequest",
    "FileSearchRequest",
    "FileWriteRequest",
    "GitWorktreeBackend",
    "GitWorktreePolicy",
    "HostExecutionBackend",
    "HostExecutionSession",
    "NetworkPolicy",
    "PatchApplyRequest",
    "ProcessHandle",
    "ResourcePolicy",
    "SecretPolicy",
    "TemporaryWorkspaceBackend",
    "TemporaryWorkspaceSession",
    "TransferPolicy",
    "UnsafePathAction",
    "WorkspaceMaterializationPolicy",
    "WorkspaceMode",
    "WorkspacePolicyError",
    "WorkspacePersistence",
]
